/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	//step1
	//need DRIVERS FOR:
	//general MCU DRIVER for address and struct definitions
	//RCC driver (optional)
	//GPIOS => MOTOR DRIVER =>4 pins Ain Bin; 2 pin GND;
	//SPI/I2C => DISTANCE AND GIRO SENSOR, MAYBE LCD
	//TIMERS => DELAYS FOR DRIVER FUNCTION
	//INDIVIDUAL SENSOR FUNCTIONS => SUCH AS DRIVE_FWD, TURN
	//UART MAYBE => BLUETOOTH MODULE COMMUNICAION
	//FIND A WAY TO RANDOMIZE

	//COULD ALSO USE SOME HAL FUNCTIONS
	//KEEP NUMBER OF HAL LIBS LOW FOR EFFICIENCY

    /* Loop forever */
	for(;;);
}
