/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "GPIO.h"
#include "RCC.h"
#include "TIMER.h"
#include "I2C.h"
#include "USART.h"
#include "MOVEMENT.h"

#include <math.h>


#define ACCEL_SENS_2G 16384.0f
#define GYRO_SENS_500DPS 65.5f
#define START_PSW	129

typedef enum {
	NOT_TURNING = 0,
	TURNING_RIGHT = 1,
	TURNING_LEFT = 2,
} DirectionState_t;

DirectionState_t direction_state = NOT_TURNING;

typedef enum {
	STATE_IDLE,
	STATE_DRIVING,
	STATE_TURNING,
	STATE_STOPPED,
} RobotState_t;

RobotState_t current_state = STATE_IDLE;

GP_TIM_Handle_t TIM2_PWM;
AD_TIM_Handle_t TIM1_TMR;
I2C_Handle_t I2C1_RX;
USART_Handle_t USART1_TXRX;
SPI_Handle_t SPI1_MPU;

typedef struct {
	int16_t X_POINT ;       // cm
	int16_t Y_POINT ;       // cm
	float ANGLE; // degrees (0–360)
} Position_t;

volatile Position_t robot_pos = {0, 0, 90.0f};


volatile float ANG_VELOCITY_MS = 0;
uint8_t INCREMENT = 0;
volatile uint16_t DRIVING_START_TIME = 0;  // global
volatile uint16_t DRIVING_ELAPSED_TIME = 0;  // global
volatile uint16_t TURNING_START_TIME = 0;  // global
volatile uint16_t TURNING_ELAPSED_TIME = 0;  // global
volatile uint8_t calc_angle_flag = 0;
volatile uint8_t send_coords_flag = 0;
volatile uint8_t wall_sensed = 0;
volatile uint8_t stop_flag = 0;

//start at origin

void init_random_seed(void);
uint16_t get_random_direction(void);
void Full_RCC_Config(void);
void Full_GPIO_Config(void);
void Full_GP_TIM_Config(void);
void Full_AD_TIM_Config(void);
void Full_I2C_Config(void);
void Full_USART_Config(void);
void Full_SPI_Config(void);
uint16_t get_elapsed_time(AD_TIM_RegDef_t *pTIMx, uint16_t start);


void ms_delay(uint32_t time_ms) {
	for(volatile uint32_t i = 0; i < time_ms * 1055; ++i) {
		__asm__("nop");
	}
}



void init_random_seed(void) {
	srand(TIM1_TMR.pTIMx->CNT);  // Seed with x,y coords/angle
}

uint16_t get_random_direction(void) {
	return 150 + (rand() % 450);  // Between 50 - 200 ms lets say
	//what is maximum rand value?
}


uint16_t get_current_time(AD_TIM_RegDef_t *pTIMx)
{
	uint16_t time = pTIMx->CNT;
	return time;
}


uint16_t get_elapsed_time(AD_TIM_RegDef_t *pTIMx, uint16_t start)
{
	uint16_t now = pTIMx->CNT;
	uint16_t elapsed;

	if (now >= start) {
		elapsed = now - start;
	} else {
		elapsed = (0xFFFF - start) + now + 1; // handle overflow
	}
	return elapsed;//error
}


uint8_t password = 0;
uint8_t coords_nr = 100;
uint8_t count = 0;
float gyro_z_bias = 0.0f;
volatile uint16_t last_angle_update_time = 0;

uint8_t AVG_BRAKING_DISTANCE = 0;
uint8_t IR_SENSOR_DISTANCE = 0;
//WHAT UNITS?


#define MPU_ADDR 0x68
#define GYRO_ZOUT_H 0x47
#define GYRO_ZOUT_L 0x48
#define GYRO_SENS_500DPS 65.5f // for FS_SEL=1



void send_coordinates()
{
	//	DRIVING_ELAPSED_TIME = get_elapsed_time(TIM1, DRIVING_START_TIME);//how long driving took place
	//	sprintf(msg2, "Drove for %u\r\n", DRIVING_ELAPSED_TIME);
	//	USART_SendData(&USART1_TXRX, (uint8_t*)msg2, strlen(msg2));

	//X_POINT = X_POINT + DRIVING_ELAPSED_TIME * speed * sinf(ANGLE * (M_PI / 180.0f);
	//X_POINT = Y_POINT + DRIVING_ELAPSED_TIME * speed * cosf(ANGLE * (M_PI / 180.0f);

	//DRIVING_ELAPSED_TIME is in ms
	//will have to modify here later once the speed of driving is measured

	robot_pos.X_POINT = robot_pos.X_POINT + ((DRIVING_ELAPSED_TIME /100)+AVG_BRAKING_DISTANCE) * sinf(robot_pos.ANGLE * (M_PI / 180.0f));
	robot_pos.Y_POINT = robot_pos.Y_POINT + ((DRIVING_ELAPSED_TIME /100)+AVG_BRAKING_DISTANCE) * cosf(robot_pos.ANGLE * (M_PI / 180.0f));

	int16_t COORD_X = robot_pos.X_POINT + (int16_t)(IR_SENSOR_DISTANCE * sinf(robot_pos.ANGLE * (M_PI / 180.0f)));
	int16_t COORD_Y = robot_pos.Y_POINT + (int16_t)(IR_SENSOR_DISTANCE * cosf(robot_pos.ANGLE * (M_PI / 180.0f)));


	DRIVING_ELAPSED_TIME = 0;
	DRIVING_START_TIME = 0;

	//Build packet
	uint8_t data[5];
	data[0] = '!'; // Start byte

	data[1] = (uint8_t)((COORD_X >> 8) & 0xFF); // X high byte
	data[2] = (uint8_t)(COORD_X & 0xFF);        // X low byte

	data[3] = (uint8_t)((COORD_Y >> 8) & 0xFF); // Y high byte
	data[4] = (uint8_t)(COORD_Y & 0xFF);        // Y low byte

	// Send 5 bytes over USART
	USART_SendData(&USART1_TXRX, data, 5);

	count++;

	if(count >= coords_nr){
		stop_flag = 1;
	}

}

void calc_angle(){
	float current_dps = MPU6500_Read_GyroZ_DPS() - gyro_z_bias;
	uint16_t current_time = get_current_time(TIM1);
	float delta_t_ms = get_elapsed_time(TIM1, last_angle_update_time);
	last_angle_update_time = current_time;

	float delta_t_s = delta_t_ms / 1000.0f;

	ANG_VELOCITY_MS = current_dps;

	float angle_change = current_dps * delta_t_s;

	robot_pos.ANGLE += angle_change;

	robot_pos.ANGLE = fmodf(robot_pos.ANGLE, 360.0f);
	if (robot_pos.ANGLE < 0) robot_pos.ANGLE += 360.0f;
}

void MPU6500_Calibrate(void) {
	long sum = 0;
	int samples = 200;
	for (int i = 0; i < samples; i++) {
		sum += MPU6500_Read_GyroZ_DPS();
		ms_delay(5);
	}
	gyro_z_bias = (float)sum / samples;
}


int main(void) {

	//while(1);

	Full_RCC_Config();
	Full_AD_TIM_Config();
	Full_GPIO_Config();
	Full_GP_TIM_Config();
	Full_USART_Config();
	Full_SPI_Config();
	init_random_seed();

	MPU6500_Init();
	MPU6500_Calibrate();
	ms_delay(500);


	while (1)
	{

		if(stop_flag){
			stop_FWD(&TIM2_PWM);
			current_state = STATE_IDLE;
			GPIO_IRQInterruptConfig(EXTI4_IRQ, DISABLE);


			for(volatile int i = 0; i < 10; i++)
			{
				GPIO_Toggle_Pin(GPIOC, GPIO_PIN_NO_13);
				ms_delay(200);
			}
		}

		if(current_state == STATE_DRIVING)
		{
			//TOGGLE_SLEEP_PIN();//to slow down car
			//really bad solution but necessary
			GPIO_Write_Pin(GPIOC,GPIO_PIN_NO_13,ENABLE);
		}
		else if(current_state == STATE_TURNING)
		{
			calc_angle();
			TOGGLE_SLEEP_PIN();//to slow down car
			//really bad solution but necessary
			GPIO_Write_Pin(GPIOC,GPIO_PIN_NO_13,DISABLE);



		}
		else if(current_state == STATE_IDLE)
		{
			USART_ReceiveData(&USART1_TXRX, &password, 1);
			ms_delay(50);
			USART_ReceiveData(&USART1_TXRX, &coords_nr, 1);
			ms_delay(50);
			if(password == START_PSW)
			{
				//START CONDITION basically
				current_state = STATE_DRIVING;
				drive_FWD(&TIM2_PWM);
				DRIVING_START_TIME = get_current_time(TIM1);

				GPIO_IRQInterruptConfig(EXTI4_IRQ, ENABLE);
			}
		}
		else if(current_state == STATE_STOPPED)
		{

		}
		ms_delay(30);

	}
	return 0;
}



void EXTI4_IRQHandler(void) //WALL SENSED
{
	stop_FWD(&TIM2_PWM);
	if(wall_sensed){
		calc_angle();
		ms_delay(50);
		calc_angle();
	}
	ms_delay(200);

	if(!GPIO_Read_Pin(GPIOA, GPIO_PIN_NO_4)){
		wall_sensed = 1;
		DRIVING_ELAPSED_TIME = get_elapsed_time(TIM1, (DRIVING_START_TIME+200));//how long driving took place

		send_coordinates();
		ms_delay(400);

		current_state = STATE_TURNING;
		TURNING_ELAPSED_TIME = 0;
		uint16_t turn_dir = get_random_direction();
		if(!(turn_dir % 2))
		{
			turn_RGT(&TIM2_PWM);
		}
		else
		{
			turn_LFT(&TIM2_PWM);
		}
		last_angle_update_time = get_current_time(TIM1);

		//calc_angle();
		//measure real median value and hardcode here
	}
	else{
		//turning stops here
		if(wall_sensed){
			wall_sensed = 0;
			last_angle_update_time+=250;
			calc_angle();
			//TURNING_ELAPSED_TIME = get_elapsed_time(TIM1,(TURNING_START_TIME+250));
			ms_delay(400);

			current_state = STATE_DRIVING;
			DRIVING_START_TIME = get_current_time(TIM1);
			drive_FWD(&TIM2_PWM);
		}else{
			drive_FWD(&TIM2_PWM);
		}
	}
	GPIO_IRQHandling(GPIO_PIN_NO_4);
}

void Full_RCC_Config(void){
	RCC_Handle_t RCC_Handle;
	RCC_Handle.pRCC = RCC;
	RCC_Handle.RCC_Config.CLK_Source = HSI;
	RCC_Handle.RCC_Config.Prescalers.AHB_Presc = AHB_DIV1;//0x0
	RCC_Handle.RCC_Config.Prescalers.APB1_Presc = APB1_DIV2;//0x4
	RCC_Handle.RCC_Config.Prescalers.APB2_Presc = APB2_DIV2;//0x4
	RCC_Clock_Config(&RCC_Handle);
}

void Full_GPIO_Config(void){
	// Testing LED Config
	// GPIO Configuration for TESTPIN PC13 = LED
	GPIO_Handle_t GpioLED;
	GpioLED.pGPIOx = GPIOC;
	GpioLED.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	GpioLED.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLED.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioLED.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLED.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	// SENSOR CONFIG
	// GPIO Configuration for GpioSensor PA4 = GPIO INTERRUPT
	GPIO_Handle_t GpioSensor;
	GpioSensor.pGPIOx = GPIOA;
	GpioSensor.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_4;
	GpioSensor.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IT_RFT;
	GpioSensor.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	GpioSensor.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;


	// SLP CONTROL CONFIG
	// GPIO Configuration for GpioSensor PB15
	GPIO_Handle_t GpioSleep;
	GpioSleep.pGPIOx = GPIOB;
	GpioSleep.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	GpioSleep.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioSleep.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioSleep.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioSleep.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	// UART CONFIG
	// GPIO Configuration for UART_TX PA9 = UART_TX
	GPIO_Handle_t GpioTX;
	GpioTX.pGPIOx = GPIOA;
	GpioTX.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_9;
	GpioTX.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;//AF07
	GpioTX.GPIO_PinConfig.GPIO_PinAltFunMode = 7;
	GpioTX.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioTX.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioTX.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	// GPIO Configuration for GpioSensor PA10 = UART_RX
	GPIO_Handle_t GpioRX;
	GpioRX.pGPIOx = GPIOA;
	GpioRX.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_10;
	GpioRX.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;//AF07
	GpioRX.GPIO_PinConfig.GPIO_PinAltFunMode = 7;
	GpioRX.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioRX.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	// GPIO Configuration for TIM2 CH4 (PA3)
	GPIO_Handle_t GpioCH4;
	GpioCH4.pGPIOx = GPIOA;
	GpioCH4.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_3;
	GpioCH4.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	GpioCH4.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;  // Set higher speed for PWM
	GpioCH4.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioCH4.GPIO_PinConfig.GPIO_PinAltFunMode = 1;  // AF1 for TIM2_PWM
	GpioCH4.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	// GPIO Configuration for TIM2 CH3 (PA2)
	GPIO_Handle_t GpioCH3;
	GpioCH3.pGPIOx = GPIOA;
	GpioCH3.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_2;
	GpioCH3.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	GpioCH3.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;  // Set higher speed for PWM
	GpioCH3.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioCH3.GPIO_PinConfig.GPIO_PinAltFunMode = 1;  // AF1 for TIM2_PWM
	GpioCH3.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	// GPIO Configuration for TIM2 CH2 (PB3)
	GPIO_Handle_t GpioCH2;
	GpioCH2.pGPIOx = GPIOB;
	GpioCH2.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_3;
	GpioCH2.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	GpioCH2.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;  // Set higher speed for PWM
	GpioCH2.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioCH2.GPIO_PinConfig.GPIO_PinAltFunMode = 1;  // AF1 for TIM2_PWM
	GpioCH2.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	// GPIO Configuration for TIM2 CH1 (PA0)
	GPIO_Handle_t GpioCH1;
	GpioCH1.pGPIOx = GPIOA;
	GpioCH1.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_0;
	GpioCH1.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	GpioCH1.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;  // Set higher speed for PWM
	GpioCH1.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioCH1.GPIO_PinConfig.GPIO_PinAltFunMode = 1;  // AF1 for TIM2_PWM
	GpioCH1.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;



	/**SPI CONFIG**/

	// SCK (PA5)
	GPIO_Handle_t GpioSCK;
	GpioSCK.pGPIOx = GPIOA;
	GpioSCK.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
	GpioSCK.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	GpioSCK.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioSCK.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioSCK.GPIO_PinConfig.GPIO_PinAltFunMode = 5; // AF5 for SPI1
	GpioSCK.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;

	// MISO (PA6)
	GPIO_Handle_t GpioMISO;
	GpioMISO.pGPIOx = GPIOA;
	GpioMISO.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_6;
	GpioMISO.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	GpioMISO.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioMISO.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioMISO.GPIO_PinConfig.GPIO_PinAltFunMode = 5;
	GpioMISO.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;


	// MOSI (PA7)
	GPIO_Handle_t GpioMOSI;
	GpioMOSI.pGPIOx = GPIOA;
	GpioMOSI.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_7;
	GpioMOSI.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	GpioMOSI.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioMOSI.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioMOSI.GPIO_PinConfig.GPIO_PinAltFunMode = 5;
	GpioMOSI.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;


	//	// NSS (PA15)
	//	GPIO_Handle_t GpioNSS;
	//	GpioNSS.pGPIOx = GPIOA;
	//	GpioNSS.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	//	GpioNSS.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_ALTFN;
	//	GpioNSS.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	//	GpioNSS.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	//	GpioNSS.GPIO_PinConfig.GPIO_PinAltFunMode = 5; // AF5 for SPI1
	//	GpioNSS.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;


	// NSS / CS (PA15) - Manual GPIO
	GPIO_Handle_t GpioCS;
	GpioCS.pGPIOx = GPIOA;
	GpioCS.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_15;
	GpioCS.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioCS.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	GpioCS.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioCS.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;


	/**SPI CONFIG**/

	// Initialize GPIO
	GPIO_Init(&GpioLED); //turns led on
	GPIO_Init(&GpioSensor);
	GPIO_Init(&GpioCH3);
	GPIO_Init(&GpioCH2);
	GPIO_Init(&GpioCH1);
	GPIO_Init(&GpioCH4);
	GPIO_Init(&GpioSCK);
	GPIO_Init(&GpioMISO);
	GPIO_Init(&GpioMOSI);
	GPIO_Init(&GpioCS);
	//GPIO_Write_Pin(GPIOA, GPIO_PIN_NO_15, ENABLE);
	GPIO_Init(&GpioTX);
	GPIO_Init(&GpioRX);
	GPIO_Init(&GpioSleep);

	//GPIO_IRQInterruptConfig(EXTI15_10_IRQ, ENABLE);
}

void Full_GP_TIM_Config(void){

	// GP Timer Configuration
	TIM2_PWM.pTIMx = TIM2;
	TIM2_PWM.GP_TIM_Config.Prescaler = 4;
	TIM2_PWM.GP_TIM_Config.Period = 3200;

	TIM2_PWM.GP_TIM_Config.CH_Setup[CH1].CH_Enabled = ENABLE;
	TIM2_PWM.GP_TIM_Config.CH_Setup[CH1].CH_Mode = PWM1;
	TIM2_PWM.GP_TIM_Config.CH_Setup[CH1].DutyCycle = 10;

	TIM2_PWM.GP_TIM_Config.CH_Setup[CH2].CH_Enabled = ENABLE;
	TIM2_PWM.GP_TIM_Config.CH_Setup[CH2].CH_Mode = PWM1;
	TIM2_PWM.GP_TIM_Config.CH_Setup[CH2].DutyCycle = 10;

	TIM2_PWM.GP_TIM_Config.CH_Setup[CH3].CH_Enabled = ENABLE;
	TIM2_PWM.GP_TIM_Config.CH_Setup[CH3].CH_Mode = PWM1;
	TIM2_PWM.GP_TIM_Config.CH_Setup[CH3].DutyCycle = 10;

	TIM2_PWM.GP_TIM_Config.CH_Setup[CH4].CH_Enabled = ENABLE;
	TIM2_PWM.GP_TIM_Config.CH_Setup[CH4].CH_Mode = PWM1;
	TIM2_PWM.GP_TIM_Config.CH_Setup[CH4].DutyCycle = 10;

	// Initialize TIM2 + CHANNELS
	GP_TIM_PWM_INIT(&TIM2_PWM);  // Initialize with CH1 disabled
}

void Full_AD_TIM_Config(void){

	// AD Timer Configuration
	TIM1_TMR.pTIMx = TIM1;

	//TIM1_CDN.AD_TIM_Config.ClockDivision = 4;
	TIM1_TMR.AD_TIM_Config.Prescaler = PRESCALER_16K;
	AD_TIM_FreeRun_INIT(&TIM1_TMR);
}



void Full_SPI_Config(void){
	SPI1_MPU.pSPIx = SPI1;
	SPI1_MPU.SPIConfig.SPI_DeviceMode = SPI_DEVICE_MODE_MASTER;
	SPI1_MPU.SPIConfig.SPI_CPHA = SPI_CPHA_LOW;
	SPI1_MPU.SPIConfig.SPI_CPOL = SPI_CPOL_LOW;;
	SPI1_MPU.SPIConfig.SPI_DFF = SPI_DFF_8BITS;
	SPI1_MPU.SPIConfig.SPI_BusConfig = SPI_BUS_CONFIG_FD;
	SPI1_MPU.SPIConfig.SPI_SSM = SPI_SSM_EN; // SSM = 1
	SPI1_MPU.SPIConfig.SPI_SclkSpeed = SPI_SCLK_SPEED_DIV8;
	SPI_Init(&SPI1_MPU);


}

void Full_USART_Config(void){

	USART1_TXRX.pUSARTx = USART1;
	USART1_TXRX.USART_Config.USART_Mode = USART_MODE_TXRX;
	USART1_TXRX.USART_Config.USART_Baud = USART_STD_BAUD_9600;
	USART1_TXRX.USART_Config.USART_WordLength = USART_WORDLEN_8BITS;
	USART1_TXRX.USART_Config.USART_NoOfStopBits	= USART_STOPBITS_1;
	USART1_TXRX.USART_Config.USART_ParityControl = USART_PARITY_DISABLE;
	//enable peripheral via cr1?

	USART_INIT(&USART1_TXRX);
	//USART1_TXRX.pUSARTx->CR1 |= (1 << 13);
}
